version: '3.7'
services:
  server:
    build:
      context: ./
    image: backend:lts
    container_name: backend
    environment:
      - MONGO_CONNECTION=yourAtlasDbConnectionstring
    volumes:
      - backendModules:/usr/src/app/node_modules
    ports:
      - 3000:3000
    networks:
      - appbackend
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.1'
          memory: 300M
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost']
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  backendModules:

networks:
  appbackend:
