version: "3.7"
services:
  server:
    build:
      context: ./
    image: backend:lts
    container_name: backend
    env_file:
      - ./.env
    volumes:
      - backendModules:/usr/src/app/node_modules
    ports:
      - 3000:3000
    networks:
      - appbackend
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 300M
      restart_policy:
        condition: on-failure
    healthcheck:
      test: ["CMD", "curl", "-f", "https://localhost:3000"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  backendModules:

networks:
  appbackend:
