# Use only for development
version: "2.4"

services:
  tests:
    build:
      context: ./
      target: test
    image: expressjs-tests
    command: jest ./tests/* --colors --maxWorkers=1 --watchAll --detectOpenHandles
    environment:
      - JWT_PRIVATE_KEY=testSecret
      - JWT_ISSUER=https://your.issuer.com
      - MONGO_CONNECTION=mongodb://db:27017/expressmongo_tests
    volumes:
      - .:/app
    user: node
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mongo
    healthcheck:
      test: '[ `echo ''db.runCommand("ping").ok'' | mongo localhost/${MONGO_DATABASE_NAME} --quiet` ] && echo 0 || echo 1'
      # interval: 30s
      # timeout: 10s
      # retries: 3
    logging:
      driver: none
