# Use only for development
version: "2.4"

services:
  # The express backend service
  backend:
    build:
      context: ./
      target: dev
    environment:
      - TZ
      - MONGO_CONNECTION
      - JWT_PRIVATE_KEY
      - JWT_REFRESH_PRIVATE_KEY
      - JWT_ISSUER
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USERNAME
      - SMTP_PASSWORD
      - FROM_EMAIL
      - FROM_NAME
    volumes:
      - .:/app
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      db:
        condition: service_healthy

  # The local mongodb service
  db:
    image: mongo:5
    environment:
      - TZ
      - MONGO_DATABASE_NAME
    volumes:
      - dbdata:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: '[ `echo ''db.runCommand("ping").ok'' | mongo localhost/${MONGO_DATABASE_NAME} --quiet` ] && echo 0 || echo 1'
      interval: 5s
      start_period: 10s
      timeout: 4s
      retries: 3

  # Db admin web interface
  dbAdmin:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=db
      - ME_CONFIG_BASICAUTH_USERNAME=root
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    ports:
      - 8081:8081
    depends_on:
      db:
        condition: service_started

  # Takes js file in the seeds folder for creating the initial state of the app
  seeder:
    image: pkosiec/mongo-seeding:latest
    volumes:
      - ./seeds:/data:ro
    environment:
      - DB_URI=${MONGO_CONNECTION}
      - DROP_DATABASE=false
      - DROP_COLLECTIONS=true
    depends_on:
      db:
        condition: service_healthy

volumes:
  # Mongo db named volume
  dbdata:
