# Use only for development
version: "3"

services:
  backend:
    build: .
    image: backend:latest
    container_name: backend
    environment:
      - MONGO_CONNECTION=yourCloudAtlasMongoDBConnectionString
    volumes:
      - .:/usr/src/app
      - backendModules:/usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start

volumes:
  backendModules:

networks:
  server:
