# Use only for development
version: "2.4"

services:
  backend:
    build:
      context: ./
      target: dev
    image: backend:latest
    container_name: backend
    env_file:
      - ./.env
    volumes:
      #- .:/app # For Linux
      - .:/app:delegated # Only for MacOsX
    ports:
      - 3000:3000
      - 9229:9229
    #command: sh scripts/dev.sh
    depends_on:
      db:
        condition: service_healthy
    networks: 
      - server

  db:
    image: mongo:latest
    container_name: backenddb
    env_file:
      - ./.env
    volumes:
      - dbdata:/data/db
    ports:
      - 27017:27017
    networks: 
      - server
    healthcheck:
      test: "mongo --quiet 127.0.0.1/test --eval 'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'"
      interval: 5s
      timeout: 5s
      retries: 12
    logging:
      driver: none

volumes:
  dbdata:

networks:
  server:
