# Use only for development
version: "3"

services:
  backend:
    build: .
    volumes:
      - .:/usr/src/app
      - backendModules:/usr/src/app/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run start

volumes:
  backendModules:
