# Use only for development
version: "2.4"

services:
  # The epxress backend service
  backend:
    build:
      context: ./
      target: dev
    image: backend:latest
    container_name: backend
    env_file:
      - ./.env
    volumes:
      #- .:/app # For Linux
      - .:/app:delegated # Only for Mac
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      db:
        condition: service_healthy

  # The local mongodb service
  db:
    image: mongo:4
    container_name: backenddb
    env_file:
      - ./.env
    volumes:
      - dbdata:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 5s
      start_period: 10s
      timeout: 4s
      retries: 3

  # Takes js file in the seeds folder for creating the initial state of the app
  seeder:
    image: pkosiec/mongo-seeding:3.3.0
    volumes:
      - ./seeds:/data
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy

volumes:
  # Mongo db named volume
  dbdata:
