# Use only for development
version: "2.4"

services:
  # The epxress backend service
  backend:
    build:
      context: ./
      target: dev
    env_file:
      - ./.env
    volumes:
      - .:/app
      #- .:/app:delegated # Only for Mac
    ports:
      - 3000:3000
      - 9229:9229
    depends_on:
      db:
        condition: service_healthy

  # The local mongodb service
  db:
    image: mongo:4
    env_file:
      - ./.env
    volumes:
      - dbdata:/data/db
    ports:
      - 27017:27017
    healthcheck:
      test: '[ `echo ''db.runCommand("ping").ok'' | mongo localhost/${MONGO_DATABASE_NAME} --quiet` ] && echo 0 || echo 1'
      interval: 5s
      start_period: 10s
      timeout: 4s
      retries: 3
    logging: # Remove this two lines in order to enable db logs
      driver: none

  # Takes js file in the seeds folder for creating the initial state of the app
  seeder:
    image: pkosiec/mongo-seeding:3.3.0
    volumes:
      - ./seeds:/data
    env_file:
      - ./.env
    environment:
      - DB_URI={MONGO_CONNECTION}
      - DROP_DATABASE=false
      - DROP_COLLECTIONS=true
    depends_on:
      db:
        condition: service_healthy

volumes:
  # Mongo db named volume
  dbdata:
