# Use only for development
version: "3.7"

services:
  backend:
    build:
      context: ./
      target: builder
      args:
        - NODE_ENV=development
    image: backend:latest
    container_name: backend
    env_file:
      - ./.env
    volumes:
      - .:/usr/src/app
    ports:
      - 3000:3000
      - 9229:9229
    command: sh scripts/dev.sh

networks:
  server:
