services:
  tests:
    build:
      context: ./
      target: test
    image: expressjs-tests
    command: jest ./tests/* --colors --runInBand --watchAll #--verbose
    environment:
      - JWT_PRIVATE_KEY=testSecret
      - JWT_REFRESH_PRIVATE_KEY=testSecret
      - JWT_ISSUER=https://your.issuer.com
      - MONGO_CONNECTION=mongodb://db/expressmongo_tests
    volumes:
      - .:/app
    user: node
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mongo
    healthcheck:
      test: '[ `echo ''db.runCommand("ping").ok'' | mongo localhost/expressmongo_tests --quiet` ] && echo 0 || echo 1'
