# Use only for development
version: "2.4"

services:
  tests:
    build:
      context: ./
      target: test
    command: npm run test:dev
    environment:
      - JWT_PRIVATE_KEY=testSecret
      - JWT_ISSUER=https://your.issuer.com
      - MONGO_CONNECTION=mongodb://db:27017/expressmongo_tests
    volumes:
      - .:/app
      #- .:/app:delegated # Only for Mac
    user: node
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mongo:4
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/expressmongo_tests --quiet
      interval: 5s
      start_period: 10s
      timeout: 4s
      retries: 3
    logging:
      driver: none